region            = "us-east-1"
instance_ami      = "ami-09e2e5104f310ffb5"
instance_user     = "core"
instance_key_file = "ssh_keys/id_rsa_instance_key.pub"
image             = "kaitoendo/ping-pong:latest"